ci: suppr black and add pylint check

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -4,11 +4,9 @@ on:
   push:
     branches:
       - 'main'
-      - 'develop'
   pull_request:
     branches:
       - 'main'
-      - 'develop'
 
 env:
   PYTHON_VERSION: "3.12.3"
@@ -34,10 +32,16 @@ jobs:
           echo "Running tests"
           make test
 
-      - name: Format code
+      - name: Run pylint and fail if score < 7.0
         run: |
-          echo "formatting the code"
-          make format
+          echo "Running pylint..."
+          score=$(pylint src tests --score=y | tee pylint-report.txt | grep "Your code has been rated at" | awk '{print $7}' | cut -d'/' -f1)
+          threshold=7.0
+          result=$(awk "BEGIN {print ($score >= $threshold) ? 0 : 1}")
+          if [ "$result" -ne 0 ]; then
+            echo "Pylint score $score is below threshold ($threshold). Failing."
+            exit 1
+          fi
       
           
   
